name: CI

on:
  push:
    branches-ignore:
      - 'l10n**'
  pull_request:

jobs:

  build-php:
    name: Build PHP
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        typo3: ['^10', '^11']
        php: ['7.3', '7.4']
        mysql: ['5.7']
        exclude:
          - typo3: '^11'
            php: '7.3'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up MySQL ${{ matrix.mysql }}
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql version: ${{ matrix.mysql }}
          mysql root password: 'root'
      - name: Set up PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
      - name: Install
        run: |
          composer require typo3/cms-core:${{ matrix.typo3 }} --no-update
          composer u --no-progress
          git checkout composer.json
      - name: Static tests
        run: |
          composer ci:static
      - name: Unit tests
        run: |
          composer ci:tests:unit
      - name: Functional tests
        run: |
          composer ci:test:functional
        env:
          COMPOSER_PROCESS_TIMEOUT: 1200
          typo3DatabaseHost: 127.0.0.1
          typo3DatabaseName: t3func
          typo3DatabasePassword: root
          typo3DatabaseUsername: root
